### ISSUE TITLE
Asynchronous route components

### ISSUE THREAD

**Issue by mxstbr** [tj/react-enroute#1]
This router looks excellent from a first, short glance.

One big feature I couldn't find were async components. This is imo quite important to allow for code splitting with webpack like this:

``` JSX
<Route
  path="/hello"
  getComponent{(callback) => {
    System.import('/helloModule.jsx')
      .then((hello) => callback(null, hello));
  }} 
/>
```

Or the old, webpack v1 way:

``` JSX
<Route
  path="/hello"
  getComponent{(callback) => {
    require.ensure([], (require) => {
      callback(null, require('./helloModule.jsx'));
    });
  }} 
/>
```

Any plans to implement that?

**Comment by tj** [comment]
Not at the moment nope! Probably best for a different module I think, my apps are pretty small so I doubt I'll end up using code splitting

**Comment by mxstbr** [comment]
Fair enough, thanks for the quick response!
