### ISSUE TITLE
Hooks?

### ISSUE THREAD

**Issue by naholyr** [tj/react-enroute#4]
Do you plan including hooks "a la react-router" or in some other form?

**Comment by tj** [comment]
No plan currently, haven't used them myself

**Comment by naholyr** [comment]
Open to a PR implementing something like this?
- Adds `onEnter(nextLocation)` and `onLeave()` attributes
  - [`onChange(…)`](https://github.com/reactjs/react-router/blob/master/docs/API.md#onchangeprevstate-nextstate-replace-callback) could come later but I'd rather start smallish
- Functions can be synchronous or asynchronous (promise)
- Hooks delay rendering

**Comment by tj** [comment]
Possibly, I haven't found any cases where you'd really need it what are you using them for? Maybe I'm doing something weird haha

**Comment by naholyr** [comment]
There are two main use cases:
- Checking credentials (you will then _not_ call the callback or _not_ return a promise, or a rejected one, and handle redirection in hook)
- Fetching data (in replacement of component lifecycle method)

**Comment by slightlytyler** [comment]
@tj where are you handling authentication for a route then? component life cycles?

**Comment by tj** [comment]
ahh yep I've been just using lifecycle methods for both in little wrapper components like `component={authenticated(Dashboard)}`. Hooks sound fine but seems easy enough to leave them out as well. I'm mostly 👍 I think since it lets you go more stateless.

I'd also consider just doing something like:

```
<Authenticated no={this.redirect} yes={this.render} />
```

in the container(s)

**Comment by jarrydfillmore** [comment]
+1!

**Comment by tj** [comment]
kinda like delegating this, closing for now
