### ISSUE TITLE
Any support for react native?

### ISSUE THREAD

**Issue by ganapativs** [tj/react-enroute#7]

**Comment by fforres** [comment]
I'd love to see that happening :D

**Comment by tj** [comment]
I haven't used react native yet so I'm not sure what the changes would need to be :D, but otherwise 👍

**Comment by ekryski** [comment]
I haven't used this in RN yet but I don't see why it wouldn't work as is.

**Comment by farwayer** [comment]
I made [simple wrapper](https://github.com/farwayer/react-native-enroute) to help react-enroute work with [react-navigation](https://github.com/react-community/react-navigation). It is very basic now because I didn't need anything except route replace and screen stack before.

**Comment by farwayer** [comment]
react-enroute plays well with React Native so I'm closing this issue.
